version: '3'

services:
  app: 
    image: web-template
    build: .
    ports:
      - 3000:3000
    # Create mappings between project directory + docker work directory
    # this allows us to enable live reloading.
    volumes: 
      - ./public:/app/public
      - ./src:/app/src
      - ./next.config.js:/app/next.config.js

